apiVersion: v1
kind: Service
metadata:
  name: motioneye-service
  namespace: motioneye
  labels:
    app: motioneye
spec:
  selector:
    app: motioneye
    tier: frontend
  ports:
    - protocol: TCP
      name: http
      port: 8765
  type: NodePort