kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motioneye-etc-pvc
  namespace: motioneye
  labels:
    app: motioneye
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 1Gi