kind: PersistentVolume
apiVersion: v1
metadata:
  name: motioneye-pv
  namespace: motioneye
  labels:
    app: motioneye
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/motioneye/data"