apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: motioneye-hpa
  namespace: motioneye
  labels:
    app: motioneye
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: motioneye-deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
status:
  observedGeneration: 1
#  lastScaleTime: <some recent time>
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageUtilization: 0
          averageValue: 0