apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: motioneye
  namespace: motioneye-http-ingress
  labels:
    app: motioneye
spec:
  ingressClassName: nginx
  rules:
    - host: motioneye.hlasta.home
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: motioneye-http-service
                port:
                  number: 8765