apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye-deployment
  namespace: motioneye
  labels:
    app: motioneye
spec:
  selector:
    matchLabels:
      app: motioneye
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: motioneye
        tier: frontend
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 44
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - lan
      volumes:
        - name: motioneye-lib-pv-storage
          persistentVolumeClaim:
            claimName: motioneye-lib-pvc
        - name: motioneye-etc-pv-storage
          persistentVolumeClaim:
            claimName: motioneye-etc-pvc
        - name: localtime
          hostPath:
            path: "/etc/localtime"
      containers:
        - name: motioneye-container
          image: dontobi/motioneye.rpi
          securityContext:
            capabilities:
              add: [ "NET_ADMIN", "SYS_ADMIN" ]
            allowPrivilegeEscalation: true
            privileged: true
          ports:
            - name: http-1
              containerPort: 8081
              protocol: TCP
            - name: http-2
              containerPort: 8082
              protocol: TCP
            - containerPort: 8765
              protocol: TCP
              name: "server"
          volumeMounts:
            - mountPath: "/etc/motioneye"
              name: motioneye-etc-pv-storage
              readOnly: false
            - mountPath: "/var/lib/motioneye"
              name: motioneye-lib-pv-storage
              readOnly: false
            - mountPath: "/motion/cam1"
              name: motioneye-lib-pv-storage
              readOnly: false
            - mountPath: "/motion/cam2"
              name: motioneye-lib-pv-storage
              readOnly: false
            - mountPath: "/etc/localtime"
              name: localtime
              readOnly: false
          env:
            - name: hostname
              value: "motioneye"
            - name: PGID
              value: "44"
            - name: PUID
              value: "0"