
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye-deployment
  namespace: motioneye
  labels:
    app: motioneye
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: motioneye
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app.kubernetes.io/part-of
                    operator: In
                    values:
                      - motioneye
      volumes:
        - name: motioneye-lib-pv-storage
          persistentVolumeClaim:
            claimName: motioneye-lib-pv-claim
        - name: motioneye-etc-pv-storage
          persistentVolumeClaim:
            claimName: motioneye-etc-pv-claim
        - name: localtime
          hostPath:
            path: "/etc/localtime"
      containers:
        - name: motioneye-container
          image: dontobi/motioneye.rpi
          ports:
            - containerPort: 8765
              protocol: TCP
              name: "server"
          volumeMounts:
            - mountPath: "/etc/motioneye"
              name: motioneye-etc-pv-storage
            - mountPath: "/var/lib/motioneye"
              name: motioneye-lib-pv-storage
            - mountPath: "/etc/localtime"
              name: localtime
          env:
            - name: hostname
              value: "motioneye"